routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::resource('gigs', 'GigController', ['except' => 'index']);
Route::resource('purchases', 'PurchaseController');
Route::get('my_orders', 'PurchaseController@orders')->name('my_orders');
Route::get('my_orders/{order}', 'PurchaseController@show_single')->name('show_single');
Route::get('my_sellings', 'PurchaseController@sellings')->name('my_sellings');
Route::get('/my_gigs', 'GigController@index')->name('my_gigs');
Route::get('/user/{name}', 'ProfileController@user_profile')->name('profile');
Route::put('/user/{id}', 'ProfileController@update')->name('profile.update');

app/Gig.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Gig extends Model
{
	public function user()
	{
		return $this->belongsTo('App\User');
	}

	public function reviews()
	{
		return $this->hasMany('App\Review');
	}

	public function purchases()
	{
		return $this->hasMany('App\Purchase');
	}
}

app/Profile.php
<?php

namespace App;

use App\User;
use Illuminate\Database\Eloquent\Model;

class Profile extends Model
{
    protected $fillable = ['user_id', 'avatar', 'about'];

    public function user()
    {
    	return $this->belongsTo('App\User');
    }
}

app/Purchase.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Purchase extends Model
{
    protected $fillable = ['user_id', 'gig_id', 'to_user_id', 'price', 'days'];

    public function gig()
    {
    	return $this->belongsTo('App\Gig');
    }
}

app/Review.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Review extends Model
{
    public function gig()
    {
    	return $this->belongsTo('App\Gig');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'username', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function gigs()
    {
    	return $this->hasMany('App\Gig');
    }

    public function profile()
    {
    	return $this->hasOne('App\Profile');
    }

    public function orders()
    {
    	return $this->hasMany('App\Gig');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/GigController.php
<?php

namespace App\Http\Controllers;

use App\Gig;
use Illuminate\Http\Request;
use Image;
use Auth;

class GigController extends Controller {

	public function __construct() {
		$this->middleware('auth', ['except' => ['index', 'show']]);
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {
		$gigs = Gig::all()->where('user_id', Auth::user()->id);
		return view( 'gig.my_gigs')->withGigs($gigs);
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create() {
		return view( 'gig.create' );
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request $request
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function store( Request $request ) {
		$this->validate( $request, array(
			'title'       => 'required|max:255',
			'price'       => 'required',
			'category'    => 'required',
			'description' => 'required'
		) );
		$gig = new Gig;

		$gig->user_id = Auth::user()->id;
		$gig->title       = $request->title;
		$gig->category    = $request->category;
		$gig->description = $request->description;
		$gig->price = $request->price;
		$gig->status = $request->status;

		if ( $request->hasFile( 'photo' ) ) {
			$image    = $request->file( 'photo' );
			$filename = time() . '.' . $image->getClientOriginalExtension();
			$location = public_path( 'img/gigs/' . $filename );
			Image::make( $image )->resize( 800, 400 )->save( $location );
			$gig->image = $filename;
		}

		$gig->save();

		return redirect()->route( 'my_gigs');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param Gig $gig
	 *
	 * @return \Illuminate\Http\Response
	 * @internal param int $id
	 *
	 */
	public function show(Gig $gig ) {
		//$gig = Gig::find($gig);

		return view('gig.gig_details')->withGig($gig);
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function edit( $id ) {

	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request $request
	 * @param  int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function update( Request $request, $id ) {
		//
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function destroy( $id ) {
		//
	}
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Gig;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function index()
    {
    	$gigs = Gig::all();
	    return view( 'home', compact('gigs', $gigs));
    }
}

app/Http/Controllers/ProfileController.php
<?php

namespace App\Http\Controllers;

use App\Profile;
use App\User;
use Illuminate\Http\Request;

class ProfileController extends Controller
{
    public function user_profile($name){
		$user = User::where('username', '=', $name)->get()->first();
		$profile = Profile::where('user_id', '=', $user->id)->get()->first();

		return view('profile')->withProfile($profile)->withName($name);
    }

    public function update(Request $request, $id){
    	$profile = Profile::where('user_id', '=', $id)->get()->first();
	    $profile->about = $request->about;

	    $profile->save();
	    return redirect()->route('my_gigs');
    }
}

app/Http/Controllers/PurchaseController.php
<?php

namespace App\Http\Controllers;

use App\Purchase;
use Illuminate\Http\Request;
use Auth;

class PurchaseController extends Controller
{
	function __construct()
	{
		$this->middleware('auth');
	}

	public function store(Request $request)
    {
        Purchase::create([
        	'user_id' => Auth::user()->id,
	        'to_user_id' => $request->to_user_id,
	        'gig_id' => $request->gig_id,
	        'price' => $request->price,
	        'days' => $request->days
        ]);

        return redirect()->route('gigs.show', $request->gig_id);
    }

    public function sellings()
    {
    	$sellings = Purchase::where('user_id', Auth::user()->id)->get();

    	return view('purchases.my_buyings')->withSellings($sellings);
    }

    public function orders()
    {
		$orders = Purchase::where('to_user_id', Auth::user()->id)->get();

	    return view('purchases.my_orders')->withOrders($orders);
    }

    public function show_single($id)
    {
    	$purchase = Purchase::find($id);

    	return view('purchases.show_single')->withPurchase($purchase);
    }
}

app/Http/Controllers/ReviewController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ReviewController extends Controller
{
    //
}

resources/views/gig/create.blade.php
@extends('layouts.base')

@section('content')
    <div class="panel panel-danger">
        <div class="panel-body">
            <form class="form-horizontal" action="{{ route('gigs.store') }}" method="post" enctype="multipart/form-data">
                {{ csrf_field() }}
                <div class="form-group">
                    <label for="title" class="col-sm-2 control-label">GIG TITLE</label>
                    <div class="col-sm-10">
                        <textarea rows="3" id="title" class="form-control" name="title"></textarea>
                    </div>
                </div>

                <div class="form-group">
                    <label for="category" class="col-sm-2 control-label">CATEGORY</label>
                    <div class="col-sm-10">
                        <select id="category" name="category" class="form-control">
                            <option value="GD">Graphis & Design</option>
                            <option value="DM">Digital & Marketing</option>
                            <option value="VA">Video & Animation</option>
                            <option value="MA">Music & Video</option>
                            <option value="PT">Programming & Tech</option>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">DESCRIPTION</label>
                    <div class="col-sm-10">
                        <textarea rows="5" class="form-control" name="description"></textarea>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">PRICE ($)</label>
                    <div class="col-sm-10">
                        <input type="number" class="form-control" value="5" name="price">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">PHOTO</label>
                    <div class="col-sm-10">
                        <input type="file" class="form-control" name="photo">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">STATUS</label>
                    <div class="col-sm-10">
                        <select name="status" class="form-control">
                            <option value="1">Active</option>
                            <option value="0">Disabled</option>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-success">Publish Gig</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/gig/gig_details.blade.php
@extends('layouts.base')

@section('content')

    <div class="row">
        <div class="col-md-8">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>{{ $gig->title }}</h3><br>
                    <p>{{ $gig->purchases->count() }} orders in queue</p>
                    <hr/>
                    <img style="width: 100%" src="{{asset('/img/gigs/' . $gig->image)}}"
                         class="img-responsive center-block">
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4>About This Gig</h4>
                </div>
                <div class="panel-body">
                    <p>{{ $gig->description }}</p>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4>Reviews</h4>
                </div>
                <div class="panel-body">
                    @if($gig->reviews->count() > 0)
                        <ul class="list-group">
                            @foreach($gig->reviews as $review)
                                <li class="list-group-item">
                                    <div class="row">
                                        <div class="col-md-2">
                                            <img src="" class="img-circle center-block"
                                                 height="60" width="60">
                                        </div>
                                        <div class="col-md-10">
                                            <h5>username</h5>
                                            <p>{{ $review->content }}</p>
                                        </div>
                                    </div>
                                </li>
                            @endforeach
                        </ul>
                    @else
                        <h3>No review yet</h3>
                    @endif
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-body">
                @if(Auth::check())
                    <!-- Modal -->
                        <div id="myModal" class="modal fade" role="dialog">
                            <div class="modal-dialog">
                                <!-- Modal content-->
                                <div class="modal-content">
                                    <div class="modal-header" style="background-color: #1b6d85; color: white">
                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                        <h4 class="modal-title">Modal Header</h4>
                                    </div>
                                    <div class="modal-body">
                                        <form method="POST" action="{{route('purchases.store')}}">
                                            {{csrf_field()}}
                                            <input name="gig_id" value="{{ $gig->id }}" hidden>
                                            <input name="to_user_id" value="{{ $gig->user->id }}" hidden>
                                            <div class="form-group">
                                                <label for="email">Price:</label>
                                                <input type="number" required name="price" min="5" max="5000" class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <label for="email">Total days:</label>
                                                <input type="number" required name="days" min="1" max="30" class="form-control">
                                            </div>
                                            <button type="submit" class="btn btn-success btn-block">
                                                Order Now
                                            </button>
                                        </form>
                                    </div>
                                    {{--<div class="modal-footer">--}}
                                        {{--<button type="button" class="btn btn-default" data-dismiss="modal">Close--}}
                                        {{--</button>--}}
                                    {{--</div>--}}
                                </div>
                            </div>
                        </div>
                        <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">
                            Order Now (${{ $gig->price }})
                        </button>
                    @else
                        You need to login to order this gig!
                    @endif

                    <div style="margin-top: 30px">
                        @if($gig->user->profile->avater == null)
                            <img src="/media/avatar.png" class="img-circle center-block" height="100" width="100">
                        @else
                            <img src="{{asset('/img/gigs/' . $gig->user->profile->avater)}}"
                                 class="img-circle center-block" height="100" width="100">
                        @endif
                    </div>
                    <a href="{{ route('profile', $gig->user->username) }}">
                        <h4 class="text-center">{{ $gig->user->username }}</h4>
                    </a>
                    {{--<hr/>--}}
                    {{--{% if gig.user.profile.about %}--}}
                    {{--<p>{{ gig.user.profile.about }}</p>--}}
                    {{--{% else %}--}}
                    {{--<p>New seller</p>--}}
                    {{--{% endif %}--}}
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/gig/my_gigs.blade.php
@extends('layouts.base')

@section('content')
    <h1 style="margin-bottom: 30px">My Gigs</h1>
    <div class="panel panel-default">
        <table class="table table-bordered table-striped">
            <thead class="bg-success">
            <tr>
                <th>Gig Title</th>
                <th>Price ($)</th>
                <th>Status</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($gigs as $gig)
                <tr>
                    <td><a href="{{ route('gigs.show', $gig->id) }}">{{ $gig->title }}</a></td>
                    <td>{{ $gig->price }}</td>
                    <td>
                        @if($gig->status)
                            Active
                        @else
                            Disabled
                        @endif
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.base')

@section('content')
    <div class="container">
        <div class="row">
            @foreach ($gigs as $gig)
                <div class="col-md-3">
                    <div class="thumbnail">
                        <a href="{{ route('gigs.show', $gig->id) }}">
                            <img src="{{asset('/img/gigs/' . $gig->image)}}">
                        </a>
                        <div class="caption">
                            <p><a href="{{ route('gigs.show', $gig->id) }}">{{ $gig->title }}</a></p>
                            <p><span>by <a href="">{{ $gig->user->username }}</a></span>
                                <b class="green pull-right">${{ $gig->price }}</b>
                            </p>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
    </div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @guest
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/layouts/base.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Laravel Fiverr Clone</title>

    <link rel="stylesheet" href="{{asset('css/app.css')}}">
    <link rel="stylesheet" href="{{asset('css/style.css')}}">

    <script src="{{asset('js/app.js')}}"></script>

</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="/">
                    <img src="{{asset('img/logo.jpg')}}" height="23">
                </a>
            </div>
            <form class="navbar-form navbar-left" role="search">
                <div class="form-group">
                    <input type="text" style="padding-right: 200px" class="form-control" placeholder="Find services">
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                @if(Auth::check())
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"
                           role="button" aria-haspopup="true" aria-expanded="false">
                            Sell & Buy
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ route('my_sellings') }}">My Sellings</a></li>
                            <li><a href="{{ route('my_orders') }}">My Orders</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"
                           role="button" aria-haspopup="true" aria-expanded="false">
                            {{ Auth::user()->username }} <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ route('gigs.create') }}">Create a gig</a></li>
                            <li><a href="{{ route('my_gigs') }}">My Gigs</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="{{ route('profile', Auth::user()->username) }}">My Profile</a></li>
                            <li role="separator" class="divider"></li>
                            <li>
                                <a href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    Logout
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                      style="display: none;">
                                    {{ csrf_field() }}
                                </form>
                            </li>
                        </ul>
                    </li>
                @else
                    <li>
                        <a href="{{ route('login') }}">Login</a>
                    </li>
                    <li>
                        <a href="{{ route('register') }}">Register</a>
                    </li>
                @endif
            </ul>
        </div>
    </div>
    <div id="category">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a href="">Graphics & Design</a></li>
                <li><a href="">Digital Marketing</a></li>
                <li><a href="">Video & Animation</a></li>
                <li><a href="">Music & Audio</a></li>
                <li><a href="">Programming & Tech</a></li>
            </ul>
        </div>
    </div>
</nav>
<div id="body" style="margin-top: 4%">
    <div class="container">
        @include('layouts.messages')
        @yield('content')
    </div>
</div>

<footer id="footer">
    <div class="container">
        <span>Laravel Fiverr clone &copy; 2017</span>
    </div>
</footer>
@yield('scripts')
</body>
</html>

resources/views/layouts/messages.blade.php
@if(Session::has('success'))

    <div class="alert alert-success" role="alert">
        <strong>success:</strong> {{Session::get('success')}}
    </div>

@endif

@if(count($errors) > 0)
    <div class="alert alert-danger" role="alert">
        <strong>Errors:</strong>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/profile.blade.php
@extends('layouts.base')

@section('content')
    @if(Auth::check() && Auth::user()->username == $name)
        <form method="post" action="{{ route('profile.update', $profile->id) }}">
            {{ csrf_field() }}
            {{ method_field('PUT') }}
            <div class="jumbotron text-center">
                <h1><b>{{ $profile->about }}</b></h1>
            </div>
            <div class="panel panel-default">
                <div class="panel-body">
                    @if($profile->avatar == null)
                        <img src="/media/avatar.png" class="img-circle" height="120" width="120">
                    @else
                        <img src="{{ $profile->avatar }}" class="img-circle" height="120" width="120">
                    @endif
                    <h3 class="text-uppercase"><b>About {{ $profile->user->username }}</b></h3>
                    <hr/>
                    @if($profile->about)
                        <input class="form-control" name="about" value="{{ $profile->about }}">
                    @else
                        <input class="form-control" name="about" placeholder="Enter you bio">
                    @endif
                    <br/>
                    <button class="btn btn-success" type="submit">Update</button>
                </div>
            </div>
        </form>
    @else
        <div class="jumbotron text-center">
            <h1><b>{{ $profile->about }}</b></h1>
        </div>
        <div class="panel panel-default">
            <div class="panel-body">
                @if($profile->avatar == null)
                    <img src="/media/avatar.png" class="img-circle" height="120" width="120">
                @else
                    <img src="{{ $profile->avatar }}" class="img-circle" height="120" width="120">
                @endif
                <h3 class="text-uppercase"><b>About {{ $profile->user->username }}</b></h3>
                <hr/>
                <p>{{ $profile->about }}</p>
            </div>
        </div>
    @endif

    <h3 class="text-uppercase" style="margin-top:50px"><b>{{ $profile->user->username }}'s gigs</b></h3>
    <div class="row">
        @foreach($profile->user->gigs as $gig)
            <div class="col-md-3">
                <div class="thumbnail">
                    <a href="{{ route('gigs.show', $gig->id) }}"><img src="{{asset('/img/gigs/' . $gig->image)}}"></a>
                    <div class="caption">
                        <p><a href="">{{ $gig->title }}</a></p>
                        <p>
                        <span>
                        <a href="">By {{ $gig->user->username }}</a>
                        </span>
                            <b class="green pull-right">$ {{ $gig->price }}</b>
                        </p>
                    </div>
                </div>
            </div>
        @endforeach
    </div>
@endsection

resources/views/purchases/my_buyings.blade.php
@extends('layouts.base')

@section('content')
    <h1 style="margin-bottom: 30px">My Buyings</h1>
    <div class="panel panel-success">
        <table class="table table-bordered table-striped">
            <thead class="bg-success">
            <tr>
                <th>Gig Title</th>
                <th>Price ($)</th>
                <th>Date</th>
            </tr>
            </thead>
            <tbody>
            @foreach($sellings as $sell)
                <tr>
                    <td><a href="">{{ $sell->gig->title }}</a></td>
                    <td>{{ $sell->gig->price }}</td>
                    <td>{{ $sell->created_at }}</td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@endsection

resources/views/purchases/my_orders.blade.php
@extends('layouts.base')

@section('content')
    <h1 style="margin-bottom: 30px">My Orders</h1>
    <div class="panel panel-success">
        <table class="table table-bordered table-striped">
            <thead class="bg-success">
            <tr>
                <th>Gig Title</th>
                <th>Price ($)</th>
                <th>Date</th>
            </tr>
            </thead>
            <tbody>
            @foreach($orders as $order)
                <tr>
                    <td><a href="{{ route('show_single', $order->id) }}">{{ $order->gig->title }}</a></td>
                    <td>{{ $order->gig->price }}</td>
                    <td>{{ $order->created_at }}</td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@endsection

resources/views/purchases/show_single.blade.php
@extends('layouts.base')

@section('content')
    <h1 style="margin-bottom: 30px">{{ $purchase->gig->title }}</h1>
    <div class="panel panel-success">
        <div class="panel-body">
            <h4>Order by: {{ $purchase->gig->user->username }}</h4>
            <p>Delivery time: within {{ $purchase->days }} days</p>
            <h3>Price: ${{ $purchase->price }}</h3>
        </div>
    </div>
@endsection